FROM 069140875175.dkr.ecr.eu-west-1.amazonaws.com/ubuntu_base_image:phusion-0.11

RUN apt-get update && \
    apt-get -y install software-properties-common \
    python3-dev \
    python3-pip \
    python3-setuptools \
    libmagickwand-dev \
    mesa-utils \
    libxkbcommon-x11-dev

RUN pip3 install --upgrade pip

# Create src dir
ENV PROJECT_DIR /py-pdf-parser

WORKDIR $PROJECT_DIR
ADD ./ $PROJECT_DIR
ADD ./imagemagick_policy.xml /etc/ImageMagick-6/policy.xml

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN chown -R optimor: $PROJECT_DIR

RUN pip install -e $PROJECT_DIR[dev]

USER optimor

RUN echo "alias python=python3" > /home/optimor/.bashrc
